/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CookingRouteImport } from './routes/cooking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShoppingIndexRouteImport } from './routes/shopping/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ShoppingVendorIdRouteImport } from './routes/shopping/$vendorId'
import { Route as SettingsVendorsRouteImport } from './routes/settings/vendors'
import { Route as SettingsTagsRouteImport } from './routes/settings/tags'
import { Route as SettingsShelvesRouteImport } from './routes/settings/shelves'
import { Route as SettingsRecipesRouteImport } from './routes/settings/recipes'
import { Route as SettingsLocationsRouteImport } from './routes/settings/locations'
import { Route as ItemsIdRouteImport } from './routes/items/$id'
import { Route as SettingsVendorsIndexRouteImport } from './routes/settings/vendors/index'
import { Route as SettingsTagsIndexRouteImport } from './routes/settings/tags/index'
import { Route as SettingsShelvesIndexRouteImport } from './routes/settings/shelves/index'
import { Route as SettingsRecipesIndexRouteImport } from './routes/settings/recipes/index'
import { Route as SettingsLocationsIndexRouteImport } from './routes/settings/locations/index'
import { Route as ItemsIdIndexRouteImport } from './routes/items/$id/index'
import { Route as SettingsVendorsIdRouteImport } from './routes/settings/vendors/$id'
import { Route as SettingsTagsIdRouteImport } from './routes/settings/tags/$id'
import { Route as SettingsShelvesShelfIdRouteImport } from './routes/settings/shelves/$shelfId'
import { Route as SettingsRecipesIdRouteImport } from './routes/settings/recipes/$id'
import { Route as ItemsIdStockRouteImport } from './routes/items/$id/stock'
import { Route as ItemsIdRelationRouteImport } from './routes/items/$id/relation'
import { Route as ItemsIdLogRouteImport } from './routes/items/$id/log'
import { Route as SettingsVendorsIdIndexRouteImport } from './routes/settings/vendors/$id/index'
import { Route as SettingsTagsIdIndexRouteImport } from './routes/settings/tags/$id/index'
import { Route as SettingsShelvesShelfIdIndexRouteImport } from './routes/settings/shelves/$shelfId/index'
import { Route as SettingsRecipesIdIndexRouteImport } from './routes/settings/recipes/$id/index'
import { Route as ItemsIdRelationIndexRouteImport } from './routes/items/$id/relation/index'
import { Route as SettingsVendorsIdItemsRouteImport } from './routes/settings/vendors/$id/items'
import { Route as SettingsTagsIdItemsRouteImport } from './routes/settings/tags/$id/items'
import { Route as SettingsShelvesShelfIdItemsRouteImport } from './routes/settings/shelves/$shelfId/items'
import { Route as SettingsShelvesShelfIdFiltersRouteImport } from './routes/settings/shelves/$shelfId/filters'
import { Route as SettingsRecipesIdItemsRouteImport } from './routes/settings/recipes/$id/items'
import { Route as ItemsIdRelationVendorsRouteImport } from './routes/items/$id/relation/vendors'
import { Route as ItemsIdRelationTagsRouteImport } from './routes/items/$id/relation/tags'
import { Route as ItemsIdRelationRecipesRouteImport } from './routes/items/$id/relation/recipes'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CookingRoute = CookingRouteImport.update({
  id: '/cooking',
  path: '/cooking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingIndexRoute = ShoppingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShoppingRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingVendorIdRoute = ShoppingVendorIdRouteImport.update({
  id: '/$vendorId',
  path: '/$vendorId',
  getParentRoute: () => ShoppingRoute,
} as any)
const SettingsVendorsRoute = SettingsVendorsRouteImport.update({
  id: '/settings/vendors',
  path: '/settings/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTagsRoute = SettingsTagsRouteImport.update({
  id: '/settings/tags',
  path: '/settings/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShelvesRoute = SettingsShelvesRouteImport.update({
  id: '/settings/shelves',
  path: '/settings/shelves',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRecipesRoute = SettingsRecipesRouteImport.update({
  id: '/settings/recipes',
  path: '/settings/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLocationsRoute = SettingsLocationsRouteImport.update({
  id: '/settings/locations',
  path: '/settings/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsVendorsIndexRoute = SettingsVendorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsVendorsRoute,
} as any)
const SettingsTagsIndexRoute = SettingsTagsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsTagsRoute,
} as any)
const SettingsShelvesIndexRoute = SettingsShelvesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsShelvesRoute,
} as any)
const SettingsRecipesIndexRoute = SettingsRecipesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRecipesRoute,
} as any)
const SettingsLocationsIndexRoute = SettingsLocationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsLocationsRoute,
} as any)
const ItemsIdIndexRoute = ItemsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItemsIdRoute,
} as any)
const SettingsVendorsIdRoute = SettingsVendorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SettingsVendorsRoute,
} as any)
const SettingsTagsIdRoute = SettingsTagsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SettingsTagsRoute,
} as any)
const SettingsShelvesShelfIdRoute = SettingsShelvesShelfIdRouteImport.update({
  id: '/$shelfId',
  path: '/$shelfId',
  getParentRoute: () => SettingsShelvesRoute,
} as any)
const SettingsRecipesIdRoute = SettingsRecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SettingsRecipesRoute,
} as any)
const ItemsIdStockRoute = ItemsIdStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => ItemsIdRoute,
} as any)
const ItemsIdRelationRoute = ItemsIdRelationRouteImport.update({
  id: '/relation',
  path: '/relation',
  getParentRoute: () => ItemsIdRoute,
} as any)
const ItemsIdLogRoute = ItemsIdLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => ItemsIdRoute,
} as any)
const SettingsVendorsIdIndexRoute = SettingsVendorsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsVendorsIdRoute,
} as any)
const SettingsTagsIdIndexRoute = SettingsTagsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsTagsIdRoute,
} as any)
const SettingsShelvesShelfIdIndexRoute =
  SettingsShelvesShelfIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsShelvesShelfIdRoute,
  } as any)
const SettingsRecipesIdIndexRoute = SettingsRecipesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRecipesIdRoute,
} as any)
const ItemsIdRelationIndexRoute = ItemsIdRelationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItemsIdRelationRoute,
} as any)
const SettingsVendorsIdItemsRoute = SettingsVendorsIdItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => SettingsVendorsIdRoute,
} as any)
const SettingsTagsIdItemsRoute = SettingsTagsIdItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => SettingsTagsIdRoute,
} as any)
const SettingsShelvesShelfIdItemsRoute =
  SettingsShelvesShelfIdItemsRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => SettingsShelvesShelfIdRoute,
  } as any)
const SettingsShelvesShelfIdFiltersRoute =
  SettingsShelvesShelfIdFiltersRouteImport.update({
    id: '/filters',
    path: '/filters',
    getParentRoute: () => SettingsShelvesShelfIdRoute,
  } as any)
const SettingsRecipesIdItemsRoute = SettingsRecipesIdItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => SettingsRecipesIdRoute,
} as any)
const ItemsIdRelationVendorsRoute = ItemsIdRelationVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => ItemsIdRelationRoute,
} as any)
const ItemsIdRelationTagsRoute = ItemsIdRelationTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ItemsIdRelationRoute,
} as any)
const ItemsIdRelationRecipesRoute = ItemsIdRelationRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => ItemsIdRelationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cooking': typeof CookingRoute
  '/onboarding': typeof OnboardingRoute
  '/shopping': typeof ShoppingRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/items/$id': typeof ItemsIdRouteWithChildren
  '/settings/locations': typeof SettingsLocationsRouteWithChildren
  '/settings/recipes': typeof SettingsRecipesRouteWithChildren
  '/settings/shelves': typeof SettingsShelvesRouteWithChildren
  '/settings/tags': typeof SettingsTagsRouteWithChildren
  '/settings/vendors': typeof SettingsVendorsRouteWithChildren
  '/shopping/$vendorId': typeof ShoppingVendorIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/shopping/': typeof ShoppingIndexRoute
  '/items/$id/log': typeof ItemsIdLogRoute
  '/items/$id/relation': typeof ItemsIdRelationRouteWithChildren
  '/items/$id/stock': typeof ItemsIdStockRoute
  '/settings/recipes/$id': typeof SettingsRecipesIdRouteWithChildren
  '/settings/shelves/$shelfId': typeof SettingsShelvesShelfIdRouteWithChildren
  '/settings/tags/$id': typeof SettingsTagsIdRouteWithChildren
  '/settings/vendors/$id': typeof SettingsVendorsIdRouteWithChildren
  '/items/$id/': typeof ItemsIdIndexRoute
  '/settings/locations/': typeof SettingsLocationsIndexRoute
  '/settings/recipes/': typeof SettingsRecipesIndexRoute
  '/settings/shelves/': typeof SettingsShelvesIndexRoute
  '/settings/tags/': typeof SettingsTagsIndexRoute
  '/settings/vendors/': typeof SettingsVendorsIndexRoute
  '/items/$id/relation/recipes': typeof ItemsIdRelationRecipesRoute
  '/items/$id/relation/tags': typeof ItemsIdRelationTagsRoute
  '/items/$id/relation/vendors': typeof ItemsIdRelationVendorsRoute
  '/settings/recipes/$id/items': typeof SettingsRecipesIdItemsRoute
  '/settings/shelves/$shelfId/filters': typeof SettingsShelvesShelfIdFiltersRoute
  '/settings/shelves/$shelfId/items': typeof SettingsShelvesShelfIdItemsRoute
  '/settings/tags/$id/items': typeof SettingsTagsIdItemsRoute
  '/settings/vendors/$id/items': typeof SettingsVendorsIdItemsRoute
  '/items/$id/relation/': typeof ItemsIdRelationIndexRoute
  '/settings/recipes/$id/': typeof SettingsRecipesIdIndexRoute
  '/settings/shelves/$shelfId/': typeof SettingsShelvesShelfIdIndexRoute
  '/settings/tags/$id/': typeof SettingsTagsIdIndexRoute
  '/settings/vendors/$id/': typeof SettingsVendorsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cooking': typeof CookingRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/shopping/$vendorId': typeof ShoppingVendorIdRoute
  '/settings': typeof SettingsIndexRoute
  '/shopping': typeof ShoppingIndexRoute
  '/items/$id/log': typeof ItemsIdLogRoute
  '/items/$id/stock': typeof ItemsIdStockRoute
  '/items/$id': typeof ItemsIdIndexRoute
  '/settings/locations': typeof SettingsLocationsIndexRoute
  '/settings/recipes': typeof SettingsRecipesIndexRoute
  '/settings/shelves': typeof SettingsShelvesIndexRoute
  '/settings/tags': typeof SettingsTagsIndexRoute
  '/settings/vendors': typeof SettingsVendorsIndexRoute
  '/items/$id/relation/recipes': typeof ItemsIdRelationRecipesRoute
  '/items/$id/relation/tags': typeof ItemsIdRelationTagsRoute
  '/items/$id/relation/vendors': typeof ItemsIdRelationVendorsRoute
  '/settings/recipes/$id/items': typeof SettingsRecipesIdItemsRoute
  '/settings/shelves/$shelfId/filters': typeof SettingsShelvesShelfIdFiltersRoute
  '/settings/shelves/$shelfId/items': typeof SettingsShelvesShelfIdItemsRoute
  '/settings/tags/$id/items': typeof SettingsTagsIdItemsRoute
  '/settings/vendors/$id/items': typeof SettingsVendorsIdItemsRoute
  '/items/$id/relation': typeof ItemsIdRelationIndexRoute
  '/settings/recipes/$id': typeof SettingsRecipesIdIndexRoute
  '/settings/shelves/$shelfId': typeof SettingsShelvesShelfIdIndexRoute
  '/settings/tags/$id': typeof SettingsTagsIdIndexRoute
  '/settings/vendors/$id': typeof SettingsVendorsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cooking': typeof CookingRoute
  '/onboarding': typeof OnboardingRoute
  '/shopping': typeof ShoppingRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/items/$id': typeof ItemsIdRouteWithChildren
  '/settings/locations': typeof SettingsLocationsRouteWithChildren
  '/settings/recipes': typeof SettingsRecipesRouteWithChildren
  '/settings/shelves': typeof SettingsShelvesRouteWithChildren
  '/settings/tags': typeof SettingsTagsRouteWithChildren
  '/settings/vendors': typeof SettingsVendorsRouteWithChildren
  '/shopping/$vendorId': typeof ShoppingVendorIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/shopping/': typeof ShoppingIndexRoute
  '/items/$id/log': typeof ItemsIdLogRoute
  '/items/$id/relation': typeof ItemsIdRelationRouteWithChildren
  '/items/$id/stock': typeof ItemsIdStockRoute
  '/settings/recipes/$id': typeof SettingsRecipesIdRouteWithChildren
  '/settings/shelves/$shelfId': typeof SettingsShelvesShelfIdRouteWithChildren
  '/settings/tags/$id': typeof SettingsTagsIdRouteWithChildren
  '/settings/vendors/$id': typeof SettingsVendorsIdRouteWithChildren
  '/items/$id/': typeof ItemsIdIndexRoute
  '/settings/locations/': typeof SettingsLocationsIndexRoute
  '/settings/recipes/': typeof SettingsRecipesIndexRoute
  '/settings/shelves/': typeof SettingsShelvesIndexRoute
  '/settings/tags/': typeof SettingsTagsIndexRoute
  '/settings/vendors/': typeof SettingsVendorsIndexRoute
  '/items/$id/relation/recipes': typeof ItemsIdRelationRecipesRoute
  '/items/$id/relation/tags': typeof ItemsIdRelationTagsRoute
  '/items/$id/relation/vendors': typeof ItemsIdRelationVendorsRoute
  '/settings/recipes/$id/items': typeof SettingsRecipesIdItemsRoute
  '/settings/shelves/$shelfId/filters': typeof SettingsShelvesShelfIdFiltersRoute
  '/settings/shelves/$shelfId/items': typeof SettingsShelvesShelfIdItemsRoute
  '/settings/tags/$id/items': typeof SettingsTagsIdItemsRoute
  '/settings/vendors/$id/items': typeof SettingsVendorsIdItemsRoute
  '/items/$id/relation/': typeof ItemsIdRelationIndexRoute
  '/settings/recipes/$id/': typeof SettingsRecipesIdIndexRoute
  '/settings/shelves/$shelfId/': typeof SettingsShelvesShelfIdIndexRoute
  '/settings/tags/$id/': typeof SettingsTagsIdIndexRoute
  '/settings/vendors/$id/': typeof SettingsVendorsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cooking'
    | '/onboarding'
    | '/shopping'
    | '/sign-in'
    | '/items/$id'
    | '/settings/locations'
    | '/settings/recipes'
    | '/settings/shelves'
    | '/settings/tags'
    | '/settings/vendors'
    | '/shopping/$vendorId'
    | '/settings/'
    | '/shopping/'
    | '/items/$id/log'
    | '/items/$id/relation'
    | '/items/$id/stock'
    | '/settings/recipes/$id'
    | '/settings/shelves/$shelfId'
    | '/settings/tags/$id'
    | '/settings/vendors/$id'
    | '/items/$id/'
    | '/settings/locations/'
    | '/settings/recipes/'
    | '/settings/shelves/'
    | '/settings/tags/'
    | '/settings/vendors/'
    | '/items/$id/relation/recipes'
    | '/items/$id/relation/tags'
    | '/items/$id/relation/vendors'
    | '/settings/recipes/$id/items'
    | '/settings/shelves/$shelfId/filters'
    | '/settings/shelves/$shelfId/items'
    | '/settings/tags/$id/items'
    | '/settings/vendors/$id/items'
    | '/items/$id/relation/'
    | '/settings/recipes/$id/'
    | '/settings/shelves/$shelfId/'
    | '/settings/tags/$id/'
    | '/settings/vendors/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cooking'
    | '/onboarding'
    | '/sign-in'
    | '/shopping/$vendorId'
    | '/settings'
    | '/shopping'
    | '/items/$id/log'
    | '/items/$id/stock'
    | '/items/$id'
    | '/settings/locations'
    | '/settings/recipes'
    | '/settings/shelves'
    | '/settings/tags'
    | '/settings/vendors'
    | '/items/$id/relation/recipes'
    | '/items/$id/relation/tags'
    | '/items/$id/relation/vendors'
    | '/settings/recipes/$id/items'
    | '/settings/shelves/$shelfId/filters'
    | '/settings/shelves/$shelfId/items'
    | '/settings/tags/$id/items'
    | '/settings/vendors/$id/items'
    | '/items/$id/relation'
    | '/settings/recipes/$id'
    | '/settings/shelves/$shelfId'
    | '/settings/tags/$id'
    | '/settings/vendors/$id'
  id:
    | '__root__'
    | '/'
    | '/cooking'
    | '/onboarding'
    | '/shopping'
    | '/sign-in'
    | '/items/$id'
    | '/settings/locations'
    | '/settings/recipes'
    | '/settings/shelves'
    | '/settings/tags'
    | '/settings/vendors'
    | '/shopping/$vendorId'
    | '/settings/'
    | '/shopping/'
    | '/items/$id/log'
    | '/items/$id/relation'
    | '/items/$id/stock'
    | '/settings/recipes/$id'
    | '/settings/shelves/$shelfId'
    | '/settings/tags/$id'
    | '/settings/vendors/$id'
    | '/items/$id/'
    | '/settings/locations/'
    | '/settings/recipes/'
    | '/settings/shelves/'
    | '/settings/tags/'
    | '/settings/vendors/'
    | '/items/$id/relation/recipes'
    | '/items/$id/relation/tags'
    | '/items/$id/relation/vendors'
    | '/settings/recipes/$id/items'
    | '/settings/shelves/$shelfId/filters'
    | '/settings/shelves/$shelfId/items'
    | '/settings/tags/$id/items'
    | '/settings/vendors/$id/items'
    | '/items/$id/relation/'
    | '/settings/recipes/$id/'
    | '/settings/shelves/$shelfId/'
    | '/settings/tags/$id/'
    | '/settings/vendors/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookingRoute: typeof CookingRoute
  OnboardingRoute: typeof OnboardingRoute
  ShoppingRoute: typeof ShoppingRouteWithChildren
  SignInRoute: typeof SignInRoute
  ItemsIdRoute: typeof ItemsIdRouteWithChildren
  SettingsLocationsRoute: typeof SettingsLocationsRouteWithChildren
  SettingsRecipesRoute: typeof SettingsRecipesRouteWithChildren
  SettingsShelvesRoute: typeof SettingsShelvesRouteWithChildren
  SettingsTagsRoute: typeof SettingsTagsRouteWithChildren
  SettingsVendorsRoute: typeof SettingsVendorsRouteWithChildren
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooking': {
      id: '/cooking'
      path: '/cooking'
      fullPath: '/cooking'
      preLoaderRoute: typeof CookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping/': {
      id: '/shopping/'
      path: '/'
      fullPath: '/shopping/'
      preLoaderRoute: typeof ShoppingIndexRouteImport
      parentRoute: typeof ShoppingRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping/$vendorId': {
      id: '/shopping/$vendorId'
      path: '/$vendorId'
      fullPath: '/shopping/$vendorId'
      preLoaderRoute: typeof ShoppingVendorIdRouteImport
      parentRoute: typeof ShoppingRoute
    }
    '/settings/vendors': {
      id: '/settings/vendors'
      path: '/settings/vendors'
      fullPath: '/settings/vendors'
      preLoaderRoute: typeof SettingsVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tags': {
      id: '/settings/tags'
      path: '/settings/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof SettingsTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/shelves': {
      id: '/settings/shelves'
      path: '/settings/shelves'
      fullPath: '/settings/shelves'
      preLoaderRoute: typeof SettingsShelvesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/recipes': {
      id: '/settings/recipes'
      path: '/settings/recipes'
      fullPath: '/settings/recipes'
      preLoaderRoute: typeof SettingsRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/locations': {
      id: '/settings/locations'
      path: '/settings/locations'
      fullPath: '/settings/locations'
      preLoaderRoute: typeof SettingsLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/vendors/': {
      id: '/settings/vendors/'
      path: '/'
      fullPath: '/settings/vendors/'
      preLoaderRoute: typeof SettingsVendorsIndexRouteImport
      parentRoute: typeof SettingsVendorsRoute
    }
    '/settings/tags/': {
      id: '/settings/tags/'
      path: '/'
      fullPath: '/settings/tags/'
      preLoaderRoute: typeof SettingsTagsIndexRouteImport
      parentRoute: typeof SettingsTagsRoute
    }
    '/settings/shelves/': {
      id: '/settings/shelves/'
      path: '/'
      fullPath: '/settings/shelves/'
      preLoaderRoute: typeof SettingsShelvesIndexRouteImport
      parentRoute: typeof SettingsShelvesRoute
    }
    '/settings/recipes/': {
      id: '/settings/recipes/'
      path: '/'
      fullPath: '/settings/recipes/'
      preLoaderRoute: typeof SettingsRecipesIndexRouteImport
      parentRoute: typeof SettingsRecipesRoute
    }
    '/settings/locations/': {
      id: '/settings/locations/'
      path: '/'
      fullPath: '/settings/locations/'
      preLoaderRoute: typeof SettingsLocationsIndexRouteImport
      parentRoute: typeof SettingsLocationsRoute
    }
    '/items/$id/': {
      id: '/items/$id/'
      path: '/'
      fullPath: '/items/$id/'
      preLoaderRoute: typeof ItemsIdIndexRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/settings/vendors/$id': {
      id: '/settings/vendors/$id'
      path: '/$id'
      fullPath: '/settings/vendors/$id'
      preLoaderRoute: typeof SettingsVendorsIdRouteImport
      parentRoute: typeof SettingsVendorsRoute
    }
    '/settings/tags/$id': {
      id: '/settings/tags/$id'
      path: '/$id'
      fullPath: '/settings/tags/$id'
      preLoaderRoute: typeof SettingsTagsIdRouteImport
      parentRoute: typeof SettingsTagsRoute
    }
    '/settings/shelves/$shelfId': {
      id: '/settings/shelves/$shelfId'
      path: '/$shelfId'
      fullPath: '/settings/shelves/$shelfId'
      preLoaderRoute: typeof SettingsShelvesShelfIdRouteImport
      parentRoute: typeof SettingsShelvesRoute
    }
    '/settings/recipes/$id': {
      id: '/settings/recipes/$id'
      path: '/$id'
      fullPath: '/settings/recipes/$id'
      preLoaderRoute: typeof SettingsRecipesIdRouteImport
      parentRoute: typeof SettingsRecipesRoute
    }
    '/items/$id/stock': {
      id: '/items/$id/stock'
      path: '/stock'
      fullPath: '/items/$id/stock'
      preLoaderRoute: typeof ItemsIdStockRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/items/$id/relation': {
      id: '/items/$id/relation'
      path: '/relation'
      fullPath: '/items/$id/relation'
      preLoaderRoute: typeof ItemsIdRelationRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/items/$id/log': {
      id: '/items/$id/log'
      path: '/log'
      fullPath: '/items/$id/log'
      preLoaderRoute: typeof ItemsIdLogRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/settings/vendors/$id/': {
      id: '/settings/vendors/$id/'
      path: '/'
      fullPath: '/settings/vendors/$id/'
      preLoaderRoute: typeof SettingsVendorsIdIndexRouteImport
      parentRoute: typeof SettingsVendorsIdRoute
    }
    '/settings/tags/$id/': {
      id: '/settings/tags/$id/'
      path: '/'
      fullPath: '/settings/tags/$id/'
      preLoaderRoute: typeof SettingsTagsIdIndexRouteImport
      parentRoute: typeof SettingsTagsIdRoute
    }
    '/settings/shelves/$shelfId/': {
      id: '/settings/shelves/$shelfId/'
      path: '/'
      fullPath: '/settings/shelves/$shelfId/'
      preLoaderRoute: typeof SettingsShelvesShelfIdIndexRouteImport
      parentRoute: typeof SettingsShelvesShelfIdRoute
    }
    '/settings/recipes/$id/': {
      id: '/settings/recipes/$id/'
      path: '/'
      fullPath: '/settings/recipes/$id/'
      preLoaderRoute: typeof SettingsRecipesIdIndexRouteImport
      parentRoute: typeof SettingsRecipesIdRoute
    }
    '/items/$id/relation/': {
      id: '/items/$id/relation/'
      path: '/'
      fullPath: '/items/$id/relation/'
      preLoaderRoute: typeof ItemsIdRelationIndexRouteImport
      parentRoute: typeof ItemsIdRelationRoute
    }
    '/settings/vendors/$id/items': {
      id: '/settings/vendors/$id/items'
      path: '/items'
      fullPath: '/settings/vendors/$id/items'
      preLoaderRoute: typeof SettingsVendorsIdItemsRouteImport
      parentRoute: typeof SettingsVendorsIdRoute
    }
    '/settings/tags/$id/items': {
      id: '/settings/tags/$id/items'
      path: '/items'
      fullPath: '/settings/tags/$id/items'
      preLoaderRoute: typeof SettingsTagsIdItemsRouteImport
      parentRoute: typeof SettingsTagsIdRoute
    }
    '/settings/shelves/$shelfId/items': {
      id: '/settings/shelves/$shelfId/items'
      path: '/items'
      fullPath: '/settings/shelves/$shelfId/items'
      preLoaderRoute: typeof SettingsShelvesShelfIdItemsRouteImport
      parentRoute: typeof SettingsShelvesShelfIdRoute
    }
    '/settings/shelves/$shelfId/filters': {
      id: '/settings/shelves/$shelfId/filters'
      path: '/filters'
      fullPath: '/settings/shelves/$shelfId/filters'
      preLoaderRoute: typeof SettingsShelvesShelfIdFiltersRouteImport
      parentRoute: typeof SettingsShelvesShelfIdRoute
    }
    '/settings/recipes/$id/items': {
      id: '/settings/recipes/$id/items'
      path: '/items'
      fullPath: '/settings/recipes/$id/items'
      preLoaderRoute: typeof SettingsRecipesIdItemsRouteImport
      parentRoute: typeof SettingsRecipesIdRoute
    }
    '/items/$id/relation/vendors': {
      id: '/items/$id/relation/vendors'
      path: '/vendors'
      fullPath: '/items/$id/relation/vendors'
      preLoaderRoute: typeof ItemsIdRelationVendorsRouteImport
      parentRoute: typeof ItemsIdRelationRoute
    }
    '/items/$id/relation/tags': {
      id: '/items/$id/relation/tags'
      path: '/tags'
      fullPath: '/items/$id/relation/tags'
      preLoaderRoute: typeof ItemsIdRelationTagsRouteImport
      parentRoute: typeof ItemsIdRelationRoute
    }
    '/items/$id/relation/recipes': {
      id: '/items/$id/relation/recipes'
      path: '/recipes'
      fullPath: '/items/$id/relation/recipes'
      preLoaderRoute: typeof ItemsIdRelationRecipesRouteImport
      parentRoute: typeof ItemsIdRelationRoute
    }
  }
}

interface ShoppingRouteChildren {
  ShoppingVendorIdRoute: typeof ShoppingVendorIdRoute
  ShoppingIndexRoute: typeof ShoppingIndexRoute
}

const ShoppingRouteChildren: ShoppingRouteChildren = {
  ShoppingVendorIdRoute: ShoppingVendorIdRoute,
  ShoppingIndexRoute: ShoppingIndexRoute,
}

const ShoppingRouteWithChildren = ShoppingRoute._addFileChildren(
  ShoppingRouteChildren,
)

interface ItemsIdRelationRouteChildren {
  ItemsIdRelationRecipesRoute: typeof ItemsIdRelationRecipesRoute
  ItemsIdRelationTagsRoute: typeof ItemsIdRelationTagsRoute
  ItemsIdRelationVendorsRoute: typeof ItemsIdRelationVendorsRoute
  ItemsIdRelationIndexRoute: typeof ItemsIdRelationIndexRoute
}

const ItemsIdRelationRouteChildren: ItemsIdRelationRouteChildren = {
  ItemsIdRelationRecipesRoute: ItemsIdRelationRecipesRoute,
  ItemsIdRelationTagsRoute: ItemsIdRelationTagsRoute,
  ItemsIdRelationVendorsRoute: ItemsIdRelationVendorsRoute,
  ItemsIdRelationIndexRoute: ItemsIdRelationIndexRoute,
}

const ItemsIdRelationRouteWithChildren = ItemsIdRelationRoute._addFileChildren(
  ItemsIdRelationRouteChildren,
)

interface ItemsIdRouteChildren {
  ItemsIdLogRoute: typeof ItemsIdLogRoute
  ItemsIdRelationRoute: typeof ItemsIdRelationRouteWithChildren
  ItemsIdStockRoute: typeof ItemsIdStockRoute
  ItemsIdIndexRoute: typeof ItemsIdIndexRoute
}

const ItemsIdRouteChildren: ItemsIdRouteChildren = {
  ItemsIdLogRoute: ItemsIdLogRoute,
  ItemsIdRelationRoute: ItemsIdRelationRouteWithChildren,
  ItemsIdStockRoute: ItemsIdStockRoute,
  ItemsIdIndexRoute: ItemsIdIndexRoute,
}

const ItemsIdRouteWithChildren =
  ItemsIdRoute._addFileChildren(ItemsIdRouteChildren)

interface SettingsLocationsRouteChildren {
  SettingsLocationsIndexRoute: typeof SettingsLocationsIndexRoute
}

const SettingsLocationsRouteChildren: SettingsLocationsRouteChildren = {
  SettingsLocationsIndexRoute: SettingsLocationsIndexRoute,
}

const SettingsLocationsRouteWithChildren =
  SettingsLocationsRoute._addFileChildren(SettingsLocationsRouteChildren)

interface SettingsRecipesIdRouteChildren {
  SettingsRecipesIdItemsRoute: typeof SettingsRecipesIdItemsRoute
  SettingsRecipesIdIndexRoute: typeof SettingsRecipesIdIndexRoute
}

const SettingsRecipesIdRouteChildren: SettingsRecipesIdRouteChildren = {
  SettingsRecipesIdItemsRoute: SettingsRecipesIdItemsRoute,
  SettingsRecipesIdIndexRoute: SettingsRecipesIdIndexRoute,
}

const SettingsRecipesIdRouteWithChildren =
  SettingsRecipesIdRoute._addFileChildren(SettingsRecipesIdRouteChildren)

interface SettingsRecipesRouteChildren {
  SettingsRecipesIdRoute: typeof SettingsRecipesIdRouteWithChildren
  SettingsRecipesIndexRoute: typeof SettingsRecipesIndexRoute
}

const SettingsRecipesRouteChildren: SettingsRecipesRouteChildren = {
  SettingsRecipesIdRoute: SettingsRecipesIdRouteWithChildren,
  SettingsRecipesIndexRoute: SettingsRecipesIndexRoute,
}

const SettingsRecipesRouteWithChildren = SettingsRecipesRoute._addFileChildren(
  SettingsRecipesRouteChildren,
)

interface SettingsShelvesShelfIdRouteChildren {
  SettingsShelvesShelfIdFiltersRoute: typeof SettingsShelvesShelfIdFiltersRoute
  SettingsShelvesShelfIdItemsRoute: typeof SettingsShelvesShelfIdItemsRoute
  SettingsShelvesShelfIdIndexRoute: typeof SettingsShelvesShelfIdIndexRoute
}

const SettingsShelvesShelfIdRouteChildren: SettingsShelvesShelfIdRouteChildren =
  {
    SettingsShelvesShelfIdFiltersRoute: SettingsShelvesShelfIdFiltersRoute,
    SettingsShelvesShelfIdItemsRoute: SettingsShelvesShelfIdItemsRoute,
    SettingsShelvesShelfIdIndexRoute: SettingsShelvesShelfIdIndexRoute,
  }

const SettingsShelvesShelfIdRouteWithChildren =
  SettingsShelvesShelfIdRoute._addFileChildren(
    SettingsShelvesShelfIdRouteChildren,
  )

interface SettingsShelvesRouteChildren {
  SettingsShelvesShelfIdRoute: typeof SettingsShelvesShelfIdRouteWithChildren
  SettingsShelvesIndexRoute: typeof SettingsShelvesIndexRoute
}

const SettingsShelvesRouteChildren: SettingsShelvesRouteChildren = {
  SettingsShelvesShelfIdRoute: SettingsShelvesShelfIdRouteWithChildren,
  SettingsShelvesIndexRoute: SettingsShelvesIndexRoute,
}

const SettingsShelvesRouteWithChildren = SettingsShelvesRoute._addFileChildren(
  SettingsShelvesRouteChildren,
)

interface SettingsTagsIdRouteChildren {
  SettingsTagsIdItemsRoute: typeof SettingsTagsIdItemsRoute
  SettingsTagsIdIndexRoute: typeof SettingsTagsIdIndexRoute
}

const SettingsTagsIdRouteChildren: SettingsTagsIdRouteChildren = {
  SettingsTagsIdItemsRoute: SettingsTagsIdItemsRoute,
  SettingsTagsIdIndexRoute: SettingsTagsIdIndexRoute,
}

const SettingsTagsIdRouteWithChildren = SettingsTagsIdRoute._addFileChildren(
  SettingsTagsIdRouteChildren,
)

interface SettingsTagsRouteChildren {
  SettingsTagsIdRoute: typeof SettingsTagsIdRouteWithChildren
  SettingsTagsIndexRoute: typeof SettingsTagsIndexRoute
}

const SettingsTagsRouteChildren: SettingsTagsRouteChildren = {
  SettingsTagsIdRoute: SettingsTagsIdRouteWithChildren,
  SettingsTagsIndexRoute: SettingsTagsIndexRoute,
}

const SettingsTagsRouteWithChildren = SettingsTagsRoute._addFileChildren(
  SettingsTagsRouteChildren,
)

interface SettingsVendorsIdRouteChildren {
  SettingsVendorsIdItemsRoute: typeof SettingsVendorsIdItemsRoute
  SettingsVendorsIdIndexRoute: typeof SettingsVendorsIdIndexRoute
}

const SettingsVendorsIdRouteChildren: SettingsVendorsIdRouteChildren = {
  SettingsVendorsIdItemsRoute: SettingsVendorsIdItemsRoute,
  SettingsVendorsIdIndexRoute: SettingsVendorsIdIndexRoute,
}

const SettingsVendorsIdRouteWithChildren =
  SettingsVendorsIdRoute._addFileChildren(SettingsVendorsIdRouteChildren)

interface SettingsVendorsRouteChildren {
  SettingsVendorsIdRoute: typeof SettingsVendorsIdRouteWithChildren
  SettingsVendorsIndexRoute: typeof SettingsVendorsIndexRoute
}

const SettingsVendorsRouteChildren: SettingsVendorsRouteChildren = {
  SettingsVendorsIdRoute: SettingsVendorsIdRouteWithChildren,
  SettingsVendorsIndexRoute: SettingsVendorsIndexRoute,
}

const SettingsVendorsRouteWithChildren = SettingsVendorsRoute._addFileChildren(
  SettingsVendorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookingRoute: CookingRoute,
  OnboardingRoute: OnboardingRoute,
  ShoppingRoute: ShoppingRouteWithChildren,
  SignInRoute: SignInRoute,
  ItemsIdRoute: ItemsIdRouteWithChildren,
  SettingsLocationsRoute: SettingsLocationsRouteWithChildren,
  SettingsRecipesRoute: SettingsRecipesRouteWithChildren,
  SettingsShelvesRoute: SettingsShelvesRouteWithChildren,
  SettingsTagsRoute: SettingsTagsRouteWithChildren,
  SettingsVendorsRoute: SettingsVendorsRouteWithChildren,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
