/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as ShelvesRouteImport } from './routes/shelves'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CookingRouteImport } from './routes/cooking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShelvesIndexRouteImport } from './routes/shelves/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ShelvesShelfIdRouteImport } from './routes/shelves/$shelfId'
import { Route as SettingsVendorsRouteImport } from './routes/settings/vendors'
import { Route as SettingsTagsRouteImport } from './routes/settings/tags'
import { Route as SettingsShelvesRouteImport } from './routes/settings/shelves'
import { Route as SettingsRecipesRouteImport } from './routes/settings/recipes'
import { Route as ItemsNewRouteImport } from './routes/items/new'
import { Route as ItemsIdRouteImport } from './routes/items/$id'
import { Route as SettingsVendorsIndexRouteImport } from './routes/settings/vendors/index'
import { Route as SettingsTagsIndexRouteImport } from './routes/settings/tags/index'
import { Route as SettingsShelvesIndexRouteImport } from './routes/settings/shelves/index'
import { Route as SettingsRecipesIndexRouteImport } from './routes/settings/recipes/index'
import { Route as ItemsIdIndexRouteImport } from './routes/items/$id/index'
import { Route as SettingsVendorsNewRouteImport } from './routes/settings/vendors/new'
import { Route as SettingsVendorsIdRouteImport } from './routes/settings/vendors/$id'
import { Route as SettingsTagsIdRouteImport } from './routes/settings/tags/$id'
import { Route as SettingsShelvesShelfIdRouteImport } from './routes/settings/shelves/$shelfId'
import { Route as SettingsRecipesNewRouteImport } from './routes/settings/recipes/new'
import { Route as SettingsRecipesIdRouteImport } from './routes/settings/recipes/$id'
import { Route as ItemsIdVendorsRouteImport } from './routes/items/$id/vendors'
import { Route as ItemsIdTagsRouteImport } from './routes/items/$id/tags'
import { Route as ItemsIdRecipesRouteImport } from './routes/items/$id/recipes'
import { Route as ItemsIdLogRouteImport } from './routes/items/$id/log'
import { Route as SettingsVendorsIdIndexRouteImport } from './routes/settings/vendors/$id/index'
import { Route as SettingsTagsIdIndexRouteImport } from './routes/settings/tags/$id/index'
import { Route as SettingsShelvesShelfIdIndexRouteImport } from './routes/settings/shelves/$shelfId/index'
import { Route as SettingsRecipesIdIndexRouteImport } from './routes/settings/recipes/$id/index'
import { Route as SettingsVendorsIdItemsRouteImport } from './routes/settings/vendors/$id/items'
import { Route as SettingsTagsIdItemsRouteImport } from './routes/settings/tags/$id/items'
import { Route as SettingsShelvesShelfIdItemsRouteImport } from './routes/settings/shelves/$shelfId/items'
import { Route as SettingsShelvesShelfIdFiltersRouteImport } from './routes/settings/shelves/$shelfId/filters'
import { Route as SettingsRecipesIdItemsRouteImport } from './routes/settings/recipes/$id/items'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelvesRoute = ShelvesRouteImport.update({
  id: '/shelves',
  path: '/shelves',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CookingRoute = CookingRouteImport.update({
  id: '/cooking',
  path: '/cooking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelvesIndexRoute = ShelvesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShelvesRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelvesShelfIdRoute = ShelvesShelfIdRouteImport.update({
  id: '/$shelfId',
  path: '/$shelfId',
  getParentRoute: () => ShelvesRoute,
} as any)
const SettingsVendorsRoute = SettingsVendorsRouteImport.update({
  id: '/settings/vendors',
  path: '/settings/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTagsRoute = SettingsTagsRouteImport.update({
  id: '/settings/tags',
  path: '/settings/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShelvesRoute = SettingsShelvesRouteImport.update({
  id: '/settings/shelves',
  path: '/settings/shelves',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRecipesRoute = SettingsRecipesRouteImport.update({
  id: '/settings/recipes',
  path: '/settings/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsNewRoute = ItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsVendorsIndexRoute = SettingsVendorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsVendorsRoute,
} as any)
const SettingsTagsIndexRoute = SettingsTagsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsTagsRoute,
} as any)
const SettingsShelvesIndexRoute = SettingsShelvesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsShelvesRoute,
} as any)
const SettingsRecipesIndexRoute = SettingsRecipesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRecipesRoute,
} as any)
const ItemsIdIndexRoute = ItemsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItemsIdRoute,
} as any)
const SettingsVendorsNewRoute = SettingsVendorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SettingsVendorsRoute,
} as any)
const SettingsVendorsIdRoute = SettingsVendorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SettingsVendorsRoute,
} as any)
const SettingsTagsIdRoute = SettingsTagsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SettingsTagsRoute,
} as any)
const SettingsShelvesShelfIdRoute = SettingsShelvesShelfIdRouteImport.update({
  id: '/$shelfId',
  path: '/$shelfId',
  getParentRoute: () => SettingsShelvesRoute,
} as any)
const SettingsRecipesNewRoute = SettingsRecipesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SettingsRecipesRoute,
} as any)
const SettingsRecipesIdRoute = SettingsRecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SettingsRecipesRoute,
} as any)
const ItemsIdVendorsRoute = ItemsIdVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => ItemsIdRoute,
} as any)
const ItemsIdTagsRoute = ItemsIdTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ItemsIdRoute,
} as any)
const ItemsIdRecipesRoute = ItemsIdRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => ItemsIdRoute,
} as any)
const ItemsIdLogRoute = ItemsIdLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => ItemsIdRoute,
} as any)
const SettingsVendorsIdIndexRoute = SettingsVendorsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsVendorsIdRoute,
} as any)
const SettingsTagsIdIndexRoute = SettingsTagsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsTagsIdRoute,
} as any)
const SettingsShelvesShelfIdIndexRoute =
  SettingsShelvesShelfIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsShelvesShelfIdRoute,
  } as any)
const SettingsRecipesIdIndexRoute = SettingsRecipesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRecipesIdRoute,
} as any)
const SettingsVendorsIdItemsRoute = SettingsVendorsIdItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => SettingsVendorsIdRoute,
} as any)
const SettingsTagsIdItemsRoute = SettingsTagsIdItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => SettingsTagsIdRoute,
} as any)
const SettingsShelvesShelfIdItemsRoute =
  SettingsShelvesShelfIdItemsRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => SettingsShelvesShelfIdRoute,
  } as any)
const SettingsShelvesShelfIdFiltersRoute =
  SettingsShelvesShelfIdFiltersRouteImport.update({
    id: '/filters',
    path: '/filters',
    getParentRoute: () => SettingsShelvesShelfIdRoute,
  } as any)
const SettingsRecipesIdItemsRoute = SettingsRecipesIdItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => SettingsRecipesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cooking': typeof CookingRoute
  '/onboarding': typeof OnboardingRoute
  '/shelves': typeof ShelvesRouteWithChildren
  '/shopping': typeof ShoppingRoute
  '/sign-in': typeof SignInRoute
  '/items/$id': typeof ItemsIdRouteWithChildren
  '/items/new': typeof ItemsNewRoute
  '/settings/recipes': typeof SettingsRecipesRouteWithChildren
  '/settings/shelves': typeof SettingsShelvesRouteWithChildren
  '/settings/tags': typeof SettingsTagsRouteWithChildren
  '/settings/vendors': typeof SettingsVendorsRouteWithChildren
  '/shelves/$shelfId': typeof ShelvesShelfIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/shelves/': typeof ShelvesIndexRoute
  '/items/$id/log': typeof ItemsIdLogRoute
  '/items/$id/recipes': typeof ItemsIdRecipesRoute
  '/items/$id/tags': typeof ItemsIdTagsRoute
  '/items/$id/vendors': typeof ItemsIdVendorsRoute
  '/settings/recipes/$id': typeof SettingsRecipesIdRouteWithChildren
  '/settings/recipes/new': typeof SettingsRecipesNewRoute
  '/settings/shelves/$shelfId': typeof SettingsShelvesShelfIdRouteWithChildren
  '/settings/tags/$id': typeof SettingsTagsIdRouteWithChildren
  '/settings/vendors/$id': typeof SettingsVendorsIdRouteWithChildren
  '/settings/vendors/new': typeof SettingsVendorsNewRoute
  '/items/$id/': typeof ItemsIdIndexRoute
  '/settings/recipes/': typeof SettingsRecipesIndexRoute
  '/settings/shelves/': typeof SettingsShelvesIndexRoute
  '/settings/tags/': typeof SettingsTagsIndexRoute
  '/settings/vendors/': typeof SettingsVendorsIndexRoute
  '/settings/recipes/$id/items': typeof SettingsRecipesIdItemsRoute
  '/settings/shelves/$shelfId/filters': typeof SettingsShelvesShelfIdFiltersRoute
  '/settings/shelves/$shelfId/items': typeof SettingsShelvesShelfIdItemsRoute
  '/settings/tags/$id/items': typeof SettingsTagsIdItemsRoute
  '/settings/vendors/$id/items': typeof SettingsVendorsIdItemsRoute
  '/settings/recipes/$id/': typeof SettingsRecipesIdIndexRoute
  '/settings/shelves/$shelfId/': typeof SettingsShelvesShelfIdIndexRoute
  '/settings/tags/$id/': typeof SettingsTagsIdIndexRoute
  '/settings/vendors/$id/': typeof SettingsVendorsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cooking': typeof CookingRoute
  '/onboarding': typeof OnboardingRoute
  '/shopping': typeof ShoppingRoute
  '/sign-in': typeof SignInRoute
  '/items/new': typeof ItemsNewRoute
  '/shelves/$shelfId': typeof ShelvesShelfIdRoute
  '/settings': typeof SettingsIndexRoute
  '/shelves': typeof ShelvesIndexRoute
  '/items/$id/log': typeof ItemsIdLogRoute
  '/items/$id/recipes': typeof ItemsIdRecipesRoute
  '/items/$id/tags': typeof ItemsIdTagsRoute
  '/items/$id/vendors': typeof ItemsIdVendorsRoute
  '/settings/recipes/new': typeof SettingsRecipesNewRoute
  '/settings/vendors/new': typeof SettingsVendorsNewRoute
  '/items/$id': typeof ItemsIdIndexRoute
  '/settings/recipes': typeof SettingsRecipesIndexRoute
  '/settings/shelves': typeof SettingsShelvesIndexRoute
  '/settings/tags': typeof SettingsTagsIndexRoute
  '/settings/vendors': typeof SettingsVendorsIndexRoute
  '/settings/recipes/$id/items': typeof SettingsRecipesIdItemsRoute
  '/settings/shelves/$shelfId/filters': typeof SettingsShelvesShelfIdFiltersRoute
  '/settings/shelves/$shelfId/items': typeof SettingsShelvesShelfIdItemsRoute
  '/settings/tags/$id/items': typeof SettingsTagsIdItemsRoute
  '/settings/vendors/$id/items': typeof SettingsVendorsIdItemsRoute
  '/settings/recipes/$id': typeof SettingsRecipesIdIndexRoute
  '/settings/shelves/$shelfId': typeof SettingsShelvesShelfIdIndexRoute
  '/settings/tags/$id': typeof SettingsTagsIdIndexRoute
  '/settings/vendors/$id': typeof SettingsVendorsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cooking': typeof CookingRoute
  '/onboarding': typeof OnboardingRoute
  '/shelves': typeof ShelvesRouteWithChildren
  '/shopping': typeof ShoppingRoute
  '/sign-in': typeof SignInRoute
  '/items/$id': typeof ItemsIdRouteWithChildren
  '/items/new': typeof ItemsNewRoute
  '/settings/recipes': typeof SettingsRecipesRouteWithChildren
  '/settings/shelves': typeof SettingsShelvesRouteWithChildren
  '/settings/tags': typeof SettingsTagsRouteWithChildren
  '/settings/vendors': typeof SettingsVendorsRouteWithChildren
  '/shelves/$shelfId': typeof ShelvesShelfIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/shelves/': typeof ShelvesIndexRoute
  '/items/$id/log': typeof ItemsIdLogRoute
  '/items/$id/recipes': typeof ItemsIdRecipesRoute
  '/items/$id/tags': typeof ItemsIdTagsRoute
  '/items/$id/vendors': typeof ItemsIdVendorsRoute
  '/settings/recipes/$id': typeof SettingsRecipesIdRouteWithChildren
  '/settings/recipes/new': typeof SettingsRecipesNewRoute
  '/settings/shelves/$shelfId': typeof SettingsShelvesShelfIdRouteWithChildren
  '/settings/tags/$id': typeof SettingsTagsIdRouteWithChildren
  '/settings/vendors/$id': typeof SettingsVendorsIdRouteWithChildren
  '/settings/vendors/new': typeof SettingsVendorsNewRoute
  '/items/$id/': typeof ItemsIdIndexRoute
  '/settings/recipes/': typeof SettingsRecipesIndexRoute
  '/settings/shelves/': typeof SettingsShelvesIndexRoute
  '/settings/tags/': typeof SettingsTagsIndexRoute
  '/settings/vendors/': typeof SettingsVendorsIndexRoute
  '/settings/recipes/$id/items': typeof SettingsRecipesIdItemsRoute
  '/settings/shelves/$shelfId/filters': typeof SettingsShelvesShelfIdFiltersRoute
  '/settings/shelves/$shelfId/items': typeof SettingsShelvesShelfIdItemsRoute
  '/settings/tags/$id/items': typeof SettingsTagsIdItemsRoute
  '/settings/vendors/$id/items': typeof SettingsVendorsIdItemsRoute
  '/settings/recipes/$id/': typeof SettingsRecipesIdIndexRoute
  '/settings/shelves/$shelfId/': typeof SettingsShelvesShelfIdIndexRoute
  '/settings/tags/$id/': typeof SettingsTagsIdIndexRoute
  '/settings/vendors/$id/': typeof SettingsVendorsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cooking'
    | '/onboarding'
    | '/shelves'
    | '/shopping'
    | '/sign-in'
    | '/items/$id'
    | '/items/new'
    | '/settings/recipes'
    | '/settings/shelves'
    | '/settings/tags'
    | '/settings/vendors'
    | '/shelves/$shelfId'
    | '/settings/'
    | '/shelves/'
    | '/items/$id/log'
    | '/items/$id/recipes'
    | '/items/$id/tags'
    | '/items/$id/vendors'
    | '/settings/recipes/$id'
    | '/settings/recipes/new'
    | '/settings/shelves/$shelfId'
    | '/settings/tags/$id'
    | '/settings/vendors/$id'
    | '/settings/vendors/new'
    | '/items/$id/'
    | '/settings/recipes/'
    | '/settings/shelves/'
    | '/settings/tags/'
    | '/settings/vendors/'
    | '/settings/recipes/$id/items'
    | '/settings/shelves/$shelfId/filters'
    | '/settings/shelves/$shelfId/items'
    | '/settings/tags/$id/items'
    | '/settings/vendors/$id/items'
    | '/settings/recipes/$id/'
    | '/settings/shelves/$shelfId/'
    | '/settings/tags/$id/'
    | '/settings/vendors/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cooking'
    | '/onboarding'
    | '/shopping'
    | '/sign-in'
    | '/items/new'
    | '/shelves/$shelfId'
    | '/settings'
    | '/shelves'
    | '/items/$id/log'
    | '/items/$id/recipes'
    | '/items/$id/tags'
    | '/items/$id/vendors'
    | '/settings/recipes/new'
    | '/settings/vendors/new'
    | '/items/$id'
    | '/settings/recipes'
    | '/settings/shelves'
    | '/settings/tags'
    | '/settings/vendors'
    | '/settings/recipes/$id/items'
    | '/settings/shelves/$shelfId/filters'
    | '/settings/shelves/$shelfId/items'
    | '/settings/tags/$id/items'
    | '/settings/vendors/$id/items'
    | '/settings/recipes/$id'
    | '/settings/shelves/$shelfId'
    | '/settings/tags/$id'
    | '/settings/vendors/$id'
  id:
    | '__root__'
    | '/'
    | '/cooking'
    | '/onboarding'
    | '/shelves'
    | '/shopping'
    | '/sign-in'
    | '/items/$id'
    | '/items/new'
    | '/settings/recipes'
    | '/settings/shelves'
    | '/settings/tags'
    | '/settings/vendors'
    | '/shelves/$shelfId'
    | '/settings/'
    | '/shelves/'
    | '/items/$id/log'
    | '/items/$id/recipes'
    | '/items/$id/tags'
    | '/items/$id/vendors'
    | '/settings/recipes/$id'
    | '/settings/recipes/new'
    | '/settings/shelves/$shelfId'
    | '/settings/tags/$id'
    | '/settings/vendors/$id'
    | '/settings/vendors/new'
    | '/items/$id/'
    | '/settings/recipes/'
    | '/settings/shelves/'
    | '/settings/tags/'
    | '/settings/vendors/'
    | '/settings/recipes/$id/items'
    | '/settings/shelves/$shelfId/filters'
    | '/settings/shelves/$shelfId/items'
    | '/settings/tags/$id/items'
    | '/settings/vendors/$id/items'
    | '/settings/recipes/$id/'
    | '/settings/shelves/$shelfId/'
    | '/settings/tags/$id/'
    | '/settings/vendors/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookingRoute: typeof CookingRoute
  OnboardingRoute: typeof OnboardingRoute
  ShelvesRoute: typeof ShelvesRouteWithChildren
  ShoppingRoute: typeof ShoppingRoute
  SignInRoute: typeof SignInRoute
  ItemsIdRoute: typeof ItemsIdRouteWithChildren
  ItemsNewRoute: typeof ItemsNewRoute
  SettingsRecipesRoute: typeof SettingsRecipesRouteWithChildren
  SettingsShelvesRoute: typeof SettingsShelvesRouteWithChildren
  SettingsTagsRoute: typeof SettingsTagsRouteWithChildren
  SettingsVendorsRoute: typeof SettingsVendorsRouteWithChildren
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves': {
      id: '/shelves'
      path: '/shelves'
      fullPath: '/shelves'
      preLoaderRoute: typeof ShelvesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooking': {
      id: '/cooking'
      path: '/cooking'
      fullPath: '/cooking'
      preLoaderRoute: typeof CookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves/': {
      id: '/shelves/'
      path: '/'
      fullPath: '/shelves/'
      preLoaderRoute: typeof ShelvesIndexRouteImport
      parentRoute: typeof ShelvesRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves/$shelfId': {
      id: '/shelves/$shelfId'
      path: '/$shelfId'
      fullPath: '/shelves/$shelfId'
      preLoaderRoute: typeof ShelvesShelfIdRouteImport
      parentRoute: typeof ShelvesRoute
    }
    '/settings/vendors': {
      id: '/settings/vendors'
      path: '/settings/vendors'
      fullPath: '/settings/vendors'
      preLoaderRoute: typeof SettingsVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tags': {
      id: '/settings/tags'
      path: '/settings/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof SettingsTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/shelves': {
      id: '/settings/shelves'
      path: '/settings/shelves'
      fullPath: '/settings/shelves'
      preLoaderRoute: typeof SettingsShelvesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/recipes': {
      id: '/settings/recipes'
      path: '/settings/recipes'
      fullPath: '/settings/recipes'
      preLoaderRoute: typeof SettingsRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/new': {
      id: '/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof ItemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/vendors/': {
      id: '/settings/vendors/'
      path: '/'
      fullPath: '/settings/vendors/'
      preLoaderRoute: typeof SettingsVendorsIndexRouteImport
      parentRoute: typeof SettingsVendorsRoute
    }
    '/settings/tags/': {
      id: '/settings/tags/'
      path: '/'
      fullPath: '/settings/tags/'
      preLoaderRoute: typeof SettingsTagsIndexRouteImport
      parentRoute: typeof SettingsTagsRoute
    }
    '/settings/shelves/': {
      id: '/settings/shelves/'
      path: '/'
      fullPath: '/settings/shelves/'
      preLoaderRoute: typeof SettingsShelvesIndexRouteImport
      parentRoute: typeof SettingsShelvesRoute
    }
    '/settings/recipes/': {
      id: '/settings/recipes/'
      path: '/'
      fullPath: '/settings/recipes/'
      preLoaderRoute: typeof SettingsRecipesIndexRouteImport
      parentRoute: typeof SettingsRecipesRoute
    }
    '/items/$id/': {
      id: '/items/$id/'
      path: '/'
      fullPath: '/items/$id/'
      preLoaderRoute: typeof ItemsIdIndexRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/settings/vendors/new': {
      id: '/settings/vendors/new'
      path: '/new'
      fullPath: '/settings/vendors/new'
      preLoaderRoute: typeof SettingsVendorsNewRouteImport
      parentRoute: typeof SettingsVendorsRoute
    }
    '/settings/vendors/$id': {
      id: '/settings/vendors/$id'
      path: '/$id'
      fullPath: '/settings/vendors/$id'
      preLoaderRoute: typeof SettingsVendorsIdRouteImport
      parentRoute: typeof SettingsVendorsRoute
    }
    '/settings/tags/$id': {
      id: '/settings/tags/$id'
      path: '/$id'
      fullPath: '/settings/tags/$id'
      preLoaderRoute: typeof SettingsTagsIdRouteImport
      parentRoute: typeof SettingsTagsRoute
    }
    '/settings/shelves/$shelfId': {
      id: '/settings/shelves/$shelfId'
      path: '/$shelfId'
      fullPath: '/settings/shelves/$shelfId'
      preLoaderRoute: typeof SettingsShelvesShelfIdRouteImport
      parentRoute: typeof SettingsShelvesRoute
    }
    '/settings/recipes/new': {
      id: '/settings/recipes/new'
      path: '/new'
      fullPath: '/settings/recipes/new'
      preLoaderRoute: typeof SettingsRecipesNewRouteImport
      parentRoute: typeof SettingsRecipesRoute
    }
    '/settings/recipes/$id': {
      id: '/settings/recipes/$id'
      path: '/$id'
      fullPath: '/settings/recipes/$id'
      preLoaderRoute: typeof SettingsRecipesIdRouteImport
      parentRoute: typeof SettingsRecipesRoute
    }
    '/items/$id/vendors': {
      id: '/items/$id/vendors'
      path: '/vendors'
      fullPath: '/items/$id/vendors'
      preLoaderRoute: typeof ItemsIdVendorsRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/items/$id/tags': {
      id: '/items/$id/tags'
      path: '/tags'
      fullPath: '/items/$id/tags'
      preLoaderRoute: typeof ItemsIdTagsRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/items/$id/recipes': {
      id: '/items/$id/recipes'
      path: '/recipes'
      fullPath: '/items/$id/recipes'
      preLoaderRoute: typeof ItemsIdRecipesRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/items/$id/log': {
      id: '/items/$id/log'
      path: '/log'
      fullPath: '/items/$id/log'
      preLoaderRoute: typeof ItemsIdLogRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/settings/vendors/$id/': {
      id: '/settings/vendors/$id/'
      path: '/'
      fullPath: '/settings/vendors/$id/'
      preLoaderRoute: typeof SettingsVendorsIdIndexRouteImport
      parentRoute: typeof SettingsVendorsIdRoute
    }
    '/settings/tags/$id/': {
      id: '/settings/tags/$id/'
      path: '/'
      fullPath: '/settings/tags/$id/'
      preLoaderRoute: typeof SettingsTagsIdIndexRouteImport
      parentRoute: typeof SettingsTagsIdRoute
    }
    '/settings/shelves/$shelfId/': {
      id: '/settings/shelves/$shelfId/'
      path: '/'
      fullPath: '/settings/shelves/$shelfId/'
      preLoaderRoute: typeof SettingsShelvesShelfIdIndexRouteImport
      parentRoute: typeof SettingsShelvesShelfIdRoute
    }
    '/settings/recipes/$id/': {
      id: '/settings/recipes/$id/'
      path: '/'
      fullPath: '/settings/recipes/$id/'
      preLoaderRoute: typeof SettingsRecipesIdIndexRouteImport
      parentRoute: typeof SettingsRecipesIdRoute
    }
    '/settings/vendors/$id/items': {
      id: '/settings/vendors/$id/items'
      path: '/items'
      fullPath: '/settings/vendors/$id/items'
      preLoaderRoute: typeof SettingsVendorsIdItemsRouteImport
      parentRoute: typeof SettingsVendorsIdRoute
    }
    '/settings/tags/$id/items': {
      id: '/settings/tags/$id/items'
      path: '/items'
      fullPath: '/settings/tags/$id/items'
      preLoaderRoute: typeof SettingsTagsIdItemsRouteImport
      parentRoute: typeof SettingsTagsIdRoute
    }
    '/settings/shelves/$shelfId/items': {
      id: '/settings/shelves/$shelfId/items'
      path: '/items'
      fullPath: '/settings/shelves/$shelfId/items'
      preLoaderRoute: typeof SettingsShelvesShelfIdItemsRouteImport
      parentRoute: typeof SettingsShelvesShelfIdRoute
    }
    '/settings/shelves/$shelfId/filters': {
      id: '/settings/shelves/$shelfId/filters'
      path: '/filters'
      fullPath: '/settings/shelves/$shelfId/filters'
      preLoaderRoute: typeof SettingsShelvesShelfIdFiltersRouteImport
      parentRoute: typeof SettingsShelvesShelfIdRoute
    }
    '/settings/recipes/$id/items': {
      id: '/settings/recipes/$id/items'
      path: '/items'
      fullPath: '/settings/recipes/$id/items'
      preLoaderRoute: typeof SettingsRecipesIdItemsRouteImport
      parentRoute: typeof SettingsRecipesIdRoute
    }
  }
}

interface ShelvesRouteChildren {
  ShelvesShelfIdRoute: typeof ShelvesShelfIdRoute
  ShelvesIndexRoute: typeof ShelvesIndexRoute
}

const ShelvesRouteChildren: ShelvesRouteChildren = {
  ShelvesShelfIdRoute: ShelvesShelfIdRoute,
  ShelvesIndexRoute: ShelvesIndexRoute,
}

const ShelvesRouteWithChildren =
  ShelvesRoute._addFileChildren(ShelvesRouteChildren)

interface ItemsIdRouteChildren {
  ItemsIdLogRoute: typeof ItemsIdLogRoute
  ItemsIdRecipesRoute: typeof ItemsIdRecipesRoute
  ItemsIdTagsRoute: typeof ItemsIdTagsRoute
  ItemsIdVendorsRoute: typeof ItemsIdVendorsRoute
  ItemsIdIndexRoute: typeof ItemsIdIndexRoute
}

const ItemsIdRouteChildren: ItemsIdRouteChildren = {
  ItemsIdLogRoute: ItemsIdLogRoute,
  ItemsIdRecipesRoute: ItemsIdRecipesRoute,
  ItemsIdTagsRoute: ItemsIdTagsRoute,
  ItemsIdVendorsRoute: ItemsIdVendorsRoute,
  ItemsIdIndexRoute: ItemsIdIndexRoute,
}

const ItemsIdRouteWithChildren =
  ItemsIdRoute._addFileChildren(ItemsIdRouteChildren)

interface SettingsRecipesIdRouteChildren {
  SettingsRecipesIdItemsRoute: typeof SettingsRecipesIdItemsRoute
  SettingsRecipesIdIndexRoute: typeof SettingsRecipesIdIndexRoute
}

const SettingsRecipesIdRouteChildren: SettingsRecipesIdRouteChildren = {
  SettingsRecipesIdItemsRoute: SettingsRecipesIdItemsRoute,
  SettingsRecipesIdIndexRoute: SettingsRecipesIdIndexRoute,
}

const SettingsRecipesIdRouteWithChildren =
  SettingsRecipesIdRoute._addFileChildren(SettingsRecipesIdRouteChildren)

interface SettingsRecipesRouteChildren {
  SettingsRecipesIdRoute: typeof SettingsRecipesIdRouteWithChildren
  SettingsRecipesNewRoute: typeof SettingsRecipesNewRoute
  SettingsRecipesIndexRoute: typeof SettingsRecipesIndexRoute
}

const SettingsRecipesRouteChildren: SettingsRecipesRouteChildren = {
  SettingsRecipesIdRoute: SettingsRecipesIdRouteWithChildren,
  SettingsRecipesNewRoute: SettingsRecipesNewRoute,
  SettingsRecipesIndexRoute: SettingsRecipesIndexRoute,
}

const SettingsRecipesRouteWithChildren = SettingsRecipesRoute._addFileChildren(
  SettingsRecipesRouteChildren,
)

interface SettingsShelvesShelfIdRouteChildren {
  SettingsShelvesShelfIdFiltersRoute: typeof SettingsShelvesShelfIdFiltersRoute
  SettingsShelvesShelfIdItemsRoute: typeof SettingsShelvesShelfIdItemsRoute
  SettingsShelvesShelfIdIndexRoute: typeof SettingsShelvesShelfIdIndexRoute
}

const SettingsShelvesShelfIdRouteChildren: SettingsShelvesShelfIdRouteChildren =
  {
    SettingsShelvesShelfIdFiltersRoute: SettingsShelvesShelfIdFiltersRoute,
    SettingsShelvesShelfIdItemsRoute: SettingsShelvesShelfIdItemsRoute,
    SettingsShelvesShelfIdIndexRoute: SettingsShelvesShelfIdIndexRoute,
  }

const SettingsShelvesShelfIdRouteWithChildren =
  SettingsShelvesShelfIdRoute._addFileChildren(
    SettingsShelvesShelfIdRouteChildren,
  )

interface SettingsShelvesRouteChildren {
  SettingsShelvesShelfIdRoute: typeof SettingsShelvesShelfIdRouteWithChildren
  SettingsShelvesIndexRoute: typeof SettingsShelvesIndexRoute
}

const SettingsShelvesRouteChildren: SettingsShelvesRouteChildren = {
  SettingsShelvesShelfIdRoute: SettingsShelvesShelfIdRouteWithChildren,
  SettingsShelvesIndexRoute: SettingsShelvesIndexRoute,
}

const SettingsShelvesRouteWithChildren = SettingsShelvesRoute._addFileChildren(
  SettingsShelvesRouteChildren,
)

interface SettingsTagsIdRouteChildren {
  SettingsTagsIdItemsRoute: typeof SettingsTagsIdItemsRoute
  SettingsTagsIdIndexRoute: typeof SettingsTagsIdIndexRoute
}

const SettingsTagsIdRouteChildren: SettingsTagsIdRouteChildren = {
  SettingsTagsIdItemsRoute: SettingsTagsIdItemsRoute,
  SettingsTagsIdIndexRoute: SettingsTagsIdIndexRoute,
}

const SettingsTagsIdRouteWithChildren = SettingsTagsIdRoute._addFileChildren(
  SettingsTagsIdRouteChildren,
)

interface SettingsTagsRouteChildren {
  SettingsTagsIdRoute: typeof SettingsTagsIdRouteWithChildren
  SettingsTagsIndexRoute: typeof SettingsTagsIndexRoute
}

const SettingsTagsRouteChildren: SettingsTagsRouteChildren = {
  SettingsTagsIdRoute: SettingsTagsIdRouteWithChildren,
  SettingsTagsIndexRoute: SettingsTagsIndexRoute,
}

const SettingsTagsRouteWithChildren = SettingsTagsRoute._addFileChildren(
  SettingsTagsRouteChildren,
)

interface SettingsVendorsIdRouteChildren {
  SettingsVendorsIdItemsRoute: typeof SettingsVendorsIdItemsRoute
  SettingsVendorsIdIndexRoute: typeof SettingsVendorsIdIndexRoute
}

const SettingsVendorsIdRouteChildren: SettingsVendorsIdRouteChildren = {
  SettingsVendorsIdItemsRoute: SettingsVendorsIdItemsRoute,
  SettingsVendorsIdIndexRoute: SettingsVendorsIdIndexRoute,
}

const SettingsVendorsIdRouteWithChildren =
  SettingsVendorsIdRoute._addFileChildren(SettingsVendorsIdRouteChildren)

interface SettingsVendorsRouteChildren {
  SettingsVendorsIdRoute: typeof SettingsVendorsIdRouteWithChildren
  SettingsVendorsNewRoute: typeof SettingsVendorsNewRoute
  SettingsVendorsIndexRoute: typeof SettingsVendorsIndexRoute
}

const SettingsVendorsRouteChildren: SettingsVendorsRouteChildren = {
  SettingsVendorsIdRoute: SettingsVendorsIdRouteWithChildren,
  SettingsVendorsNewRoute: SettingsVendorsNewRoute,
  SettingsVendorsIndexRoute: SettingsVendorsIndexRoute,
}

const SettingsVendorsRouteWithChildren = SettingsVendorsRoute._addFileChildren(
  SettingsVendorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookingRoute: CookingRoute,
  OnboardingRoute: OnboardingRoute,
  ShelvesRoute: ShelvesRouteWithChildren,
  ShoppingRoute: ShoppingRoute,
  SignInRoute: SignInRoute,
  ItemsIdRoute: ItemsIdRouteWithChildren,
  ItemsNewRoute: ItemsNewRoute,
  SettingsRecipesRoute: SettingsRecipesRouteWithChildren,
  SettingsShelvesRoute: SettingsShelvesRouteWithChildren,
  SettingsTagsRoute: SettingsTagsRouteWithChildren,
  SettingsVendorsRoute: SettingsVendorsRouteWithChildren,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
