import { test, expect, type Page, type APIRequestContext } from '@playwright/test'
import { CLOUD_GRAPHQL_URL, CLOUD_SERVER_URL, CLOUD_WEB_URL, E2E_USER_ID } from '../../constants'
import { ItemPage } from '../../pages/ItemPage'
import { PantryPage } from '../../pages/PantryPage'
import { RecipeDetailPage } from '../../pages/settings/RecipeDetailPage'
import { RecipesPage } from '../../pages/settings/RecipesPage'

// Seed a recipe (and optionally items) directly into IndexedDB.
// Navigate to '/' first so Dexie initialises the DB schema.
async function seedRecipe(
  page: Page,
  recipeName: string,
  items: { name: string; defaultAmount: number }[] = [],
): Promise<{ recipeId: string; itemIds: string[] }> {
  await page.goto('/')

  const recipeId = crypto.randomUUID()
  const itemIds = items.map(() => crypto.randomUUID())
  const now = new Date().toISOString()

  await page.evaluate(
    async ({ recipeId, itemIds, recipeName, items, now }) => {
      const db = await new Promise<IDBDatabase>((resolve, reject) => {
        const req = indexedDB.open('Player1Inventory')
        req.onsuccess = () => resolve(req.result)
        req.onerror = () => reject(req.error)
      })

      const put = (storeName: string, record: object) =>
        new Promise<void>((resolve, reject) => {
          const tx = db.transaction(storeName, 'readwrite')
          const req = tx.objectStore(storeName).put(record)
          req.onsuccess = () => resolve()
          req.onerror = () => reject(req.error)
        })

      // Seed items first (recipe references them)
      for (let i = 0; i < items.length; i++) {
        await put('items', {
          id: itemIds[i],
          name: items[i].name,
          tagIds: [],
          vendorIds: [],
          targetUnit: 'package',
          targetQuantity: 0,
          refillThreshold: 0,
          packedQuantity: 0,
          unpackedQuantity: 0,
          consumeAmount: 1,
          createdAt: new Date(now),
          updatedAt: new Date(now),
        })
      }

      // Seed recipe with item references
      await put('recipes', {
        id: recipeId,
        name: recipeName,
        items: items.map((item, i) => ({
          itemId: itemIds[i],
          defaultAmount: item.defaultAmount,
        })),
        createdAt: new Date(now),
        updatedAt: new Date(now),
      })
    },
    { recipeId, itemIds, recipeName, items, now },
  )

  return { recipeId, itemIds }
}

// Seed a standalone item (not linked to any recipe)
async function seedItem(page: Page, name: string): Promise<string> {
  await page.goto('/')

  const itemId = crypto.randomUUID()
  const now = new Date().toISOString()

  await page.evaluate(
    async ({ itemId, name, now }) => {
      const db = await new Promise<IDBDatabase>((resolve, reject) => {
        const req = indexedDB.open('Player1Inventory')
        req.onsuccess = () => resolve(req.result)
        req.onerror = () => reject(req.error)
      })
      await new Promise<void>((resolve, reject) => {
        const tx = db.transaction('items', 'readwrite')
        const req = tx.objectStore('items').put({
          id: itemId,
          name,
          tagIds: [],
          vendorIds: [],
          targetUnit: 'package',
          targetQuantity: 0,
          refillThreshold: 0,
          packedQuantity: 0,
          unpackedQuantity: 0,
          consumeAmount: 1,
          createdAt: new Date(now),
          updatedAt: new Date(now),
        })
        req.onsuccess = () => resolve()
        req.onerror = () => reject(req.error)
      })
    },
    { itemId, name, now },
  )

  return itemId
}

// Seed a recipe (and optionally items) via the GraphQL API for cloud mode.
// Returns the IDs generated by the server.
async function seedRecipeViaApi(
  request: APIRequestContext,
  recipeName: string,
  items: { name: string; defaultAmount: number }[] = [],
): Promise<{ recipeId: string; itemIds: string[] }> {
  const itemIds: string[] = []

  for (const item of items) {
    const res = await request.post(CLOUD_GRAPHQL_URL, {
      headers: { 'x-e2e-user-id': E2E_USER_ID, 'Content-Type': 'application/json' },
      data: {
        query: 'mutation CreateItem($name: String!) { createItem(name: $name) { id } }',
        variables: { name: item.name },
      },
    })
    const json = await res.json()
    itemIds.push(json.data.createItem.id)
  }

  const res = await request.post(CLOUD_GRAPHQL_URL, {
    headers: { 'x-e2e-user-id': E2E_USER_ID, 'Content-Type': 'application/json' },
    data: {
      query: `mutation CreateRecipe($name: String!, $items: [RecipeItemInput!]) {
        createRecipe(name: $name, items: $items) { id }
      }`,
      variables: {
        name: recipeName,
        items: items.map((item, i) => ({ itemId: itemIds[i], defaultAmount: item.defaultAmount })),
      },
    },
  })
  const json = await res.json()
  const recipeId = json.data.createRecipe.id

  return { recipeId, itemIds }
}

test.beforeEach(async ({ request, baseURL }) => {
  if (baseURL === CLOUD_WEB_URL) {
    await request.delete(`${CLOUD_SERVER_URL}/e2e/cleanup`, {
      headers: { 'x-e2e-user-id': E2E_USER_ID },
    })
  }
})

test.afterEach(async ({ page, request, baseURL }) => {
  if (baseURL === CLOUD_WEB_URL) {
    // Cloud mode: delete all test data from MongoDB via the E2E cleanup endpoint.
    await request.delete(`${CLOUD_SERVER_URL}/e2e/cleanup`, {
      headers: { 'x-e2e-user-id': E2E_USER_ID },
    })
  } else {
    // Local mode: clear IndexedDB, localStorage, and sessionStorage.
    await page.goto('/')
    await page.evaluate(async () => {
      const dbs = await indexedDB.databases()
      await Promise.all(
        dbs.map(({ name }) => {
          return new Promise<void>((resolve, reject) => {
            if (!name) {
              resolve()
              return
            }
            const req = indexedDB.deleteDatabase(name)
            req.onsuccess = () => resolve()
            req.onerror = () => reject(req.error)
            req.onblocked = () => {
              console.warn(`[afterEach] IndexedDB delete blocked for "${name}"...`)
              resolve()
            }
          })
        }),
      )
      localStorage.clear()
      sessionStorage.clear()
    })
  }
})

test('user can create a recipe', async ({ page }) => {
  const recipes = new RecipesPage(page)

  // Given: recipes list is empty
  await recipes.navigateTo()

  // When: user clicks "New Recipe", fills name, and saves
  await recipes.clickNewRecipe()
  // URL becomes /settings/recipes/new?name= (query param from validateSearch)
  await page.waitForURL((url) => url.pathname === '/settings/recipes/new')
  await recipes.fillRecipeName('Pancakes')
  await recipes.clickSave()

  // Wait for redirect to the detail page after save
  await page.waitForURL((url) => url.pathname.startsWith('/settings/recipes/') && url.pathname !== '/settings/recipes/new')

  // Then: navigate back to list to verify the recipe appears
  await recipes.navigateTo()
  await expect(recipes.getRecipeCard('Pancakes')).toBeVisible()
})

test('user can delete a recipe', async ({ page, baseURL }) => {
  const recipes = new RecipesPage(page)

  if (baseURL === CLOUD_WEB_URL) {
    // Cloud: create via UI (data goes to MongoDB)
    await recipes.navigateTo()
    await recipes.clickNewRecipe()
    await page.waitForURL((url) => url.pathname === '/settings/recipes/new')
    await recipes.fillRecipeName('Pancakes')
    await recipes.clickSave()
    await page.waitForURL((url) => url.pathname.startsWith('/settings/recipes/') && url.pathname !== '/settings/recipes/new')
    await recipes.navigateTo()
  } else {
    // Local: seed via IndexedDB and navigate
    await seedRecipe(page, 'Pancakes')
    await recipes.navigateTo()
  }

  await expect(recipes.getRecipeCard('Pancakes')).toBeVisible()

  // When: user clicks delete and confirms
  await recipes.clickDeleteRecipe('Pancakes')
  await recipes.confirmDelete()

  // Then: "Pancakes" card is gone
  await expect(recipes.getRecipeCard('Pancakes')).not.toBeVisible()
})

test('user can navigate to recipe detail after creating', async ({ page }) => {
  const recipes = new RecipesPage(page)

  // Given: recipes list is empty
  await recipes.navigateTo()

  // When: user creates "Pancakes"
  await recipes.clickNewRecipe()
  await recipes.fillRecipeName('Pancakes')
  await recipes.clickSave()

  // Then: URL is /settings/recipes/<id> (detail page, not the new page)
  await expect(page).toHaveURL(/\/settings\/recipes\/[^/]+$/)
})

test('user can assign and unassign an item on Items tab', async ({ page, baseURL }) => {
  const detail = new RecipeDetailPage(page)

  let recipeId: string

  if (baseURL === CLOUD_WEB_URL) {
    // Cloud: create recipe via UI, then create item via pantry UI
    const recipes = new RecipesPage(page)
    const pantry = new PantryPage(page)
    const item = new ItemPage(page)

    await recipes.navigateTo()
    await recipes.clickNewRecipe()
    await page.waitForURL((url) => url.pathname === '/settings/recipes/new')
    await recipes.fillRecipeName('Pancakes')
    await recipes.clickSave()
    await page.waitForURL((url) => url.pathname.startsWith('/settings/recipes/') && url.pathname !== '/settings/recipes/new')
    recipeId = new URL(page.url()).pathname.split('/').filter(Boolean).pop()!

    await pantry.navigateTo()
    await pantry.clickAddItem()
    await item.fillName('Eggs')
    await item.save()

    await detail.navigateToItems(recipeId)
  } else {
    // Local: seed recipe and item directly into IndexedDB
    const result = await seedRecipe(page, 'Pancakes')
    recipeId = result.recipeId
    await seedItem(page, 'Eggs')
    await detail.navigateToItems(recipeId)
  }

  // Then: "Eggs" shows as unassigned (Add checkbox visible)
  await expect(detail.getItemCheckbox('Eggs')).toBeVisible()

  // When: check (assign)
  await detail.toggleItem('Eggs')

  // Then: "Eggs" shows as assigned (Remove checkbox visible)
  await expect(detail.getAssignedItemCheckbox('Eggs')).toBeVisible()

  // When: uncheck (unassign)
  await detail.toggleItem('Eggs')

  // Then: back to unassigned
  await expect(detail.getItemCheckbox('Eggs')).toBeVisible()
})

test('user can adjust default amount for an assigned item', async ({ page, request, baseURL }) => {
  const detail = new RecipeDetailPage(page)

  let recipeId: string

  if (baseURL === CLOUD_WEB_URL) {
    // Cloud: seed via GraphQL API to set defaultAmount=2 precisely
    const result = await seedRecipeViaApi(request, 'Pancakes', [{ name: 'Flour', defaultAmount: 2 }])
    recipeId = result.recipeId
  } else {
    // Local: seed via IndexedDB
    const result = await seedRecipe(page, 'Pancakes', [{ name: 'Flour', defaultAmount: 2 }])
    recipeId = result.recipeId
  }

  // When: navigate to Items tab
  await detail.navigateToItems(recipeId)

  // Then: Flour is assigned (Remove checkbox visible) and amount display shows 2
  await expect(detail.getAssignedItemCheckbox('Flour')).toBeVisible()
  await expect(detail.getAmountDisplay('Flour')).toHaveText('2')

  // When: click + (increase)
  await detail.clickIncreaseAmount('Flour')

  // Then: amount is 3 (step = consumeAmount = 1)
  await expect(detail.getAmountDisplay('Flour')).toHaveText('3')

  // When: click − twice
  await detail.clickDecreaseAmount('Flour')
  await detail.clickDecreaseAmount('Flour')

  // Then: amount is 1
  await expect(detail.getAmountDisplay('Flour')).toHaveText('1')
})

test('user can edit recipe name on Info tab', async ({ page, baseURL }) => {
  const detail = new RecipeDetailPage(page)

  let recipeId: string

  if (baseURL === CLOUD_WEB_URL) {
    // Cloud: create recipe via UI and extract ID from URL
    const recipes = new RecipesPage(page)
    await recipes.navigateTo()
    await recipes.clickNewRecipe()
    await page.waitForURL((url) => url.pathname === '/settings/recipes/new')
    await recipes.fillRecipeName('Pancakes')
    await recipes.clickSave()
    await page.waitForURL((url) => url.pathname.startsWith('/settings/recipes/') && url.pathname !== '/settings/recipes/new')
    recipeId = new URL(page.url()).pathname.split('/').filter(Boolean).pop()!
  } else {
    // Local: seed via IndexedDB and navigate by ID
    const result = await seedRecipe(page, 'Pancakes')
    recipeId = result.recipeId
    await detail.navigateTo(recipeId)
  }

  // When: navigate to detail page (Info tab is default)
  await detail.navigateTo(recipeId)

  // And: change name to "Waffles" and save
  await detail.fillName('Waffles')
  await detail.clickSave()

  // Wait for goBack() navigation to complete (save triggers goBack which leaves the detail page)
  await page.waitForURL((url) => !url.pathname.endsWith(`/${recipeId}`))

  // Then: re-navigate to detail to verify persistence
  await detail.navigateTo(recipeId)
  await page.waitForURL((url) => url.pathname.includes(recipeId))
  await expect(page.getByLabel('Name')).toHaveValue('Waffles')
})
