query GetItem($id: ID!) {
  item(id: $id) {
    id
    name
    tagIds
    vendorIds
    packageUnit
    measurementUnit
    amountPerPackage
    targetUnit
    consumeAmount
    expirationMode
    estimatedDueDays
    expirationThreshold
    userId
    createdAt
    updatedAt
  }
}

query GetItems {
  items {
    id
    name
    tagIds
    vendorIds
    packageUnit
    measurementUnit
    amountPerPackage
    targetUnit
    consumeAmount
    expirationMode
    estimatedDueDays
    expirationThreshold
    userId
    createdAt
    updatedAt
  }
}

mutation CreateItem($input: CreateItemInput!) {
  createItem(input: $input) {
    id
    name
    tagIds
    targetUnit
    consumeAmount
    expirationMode
    estimatedDueDays
    expirationThreshold
    createdAt
    updatedAt
  }
}

mutation UpdateItem($id: ID!, $input: UpdateItemInput!) {
  updateItem(id: $id, input: $input) {
    id
    name
    tagIds
    vendorIds
    packageUnit
    measurementUnit
    amountPerPackage
    targetUnit
    consumeAmount
    expirationMode
    estimatedDueDays
    expirationThreshold
    updatedAt
  }
}

mutation DeleteItem($id: ID!) {
  deleteItem(id: $id)
}

query ItemCountByTag($tagId: String!) {
  itemCountByTag(tagId: $tagId)
}

query ItemCountByVendor($vendorId: String!) {
  itemCountByVendor(vendorId: $vendorId)
}

query ItemCountByRecipe($recipeId: String!) {
  itemCountByRecipe(recipeId: $recipeId)
}
