/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsTagsRouteImport } from './routes/settings/tags'
import { Route as ItemsNewRouteImport } from './routes/items/new'
import { Route as ItemsIdRouteImport } from './routes/items/$id'
import { Route as ItemsIdIndexRouteImport } from './routes/items/$id/index'
import { Route as ItemsIdTagsRouteImport } from './routes/items/$id/tags'
import { Route as ItemsIdLogRouteImport } from './routes/items/$id.log'
import { Route as ItemsIdInfoRouteImport } from './routes/items/$id/info'

const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTagsRoute = SettingsTagsRouteImport.update({
  id: '/settings/tags',
  path: '/settings/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsNewRoute = ItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdIndexRoute = ItemsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItemsIdRoute,
} as any)
const ItemsIdTagsRoute = ItemsIdTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ItemsIdRoute,
} as any)
const ItemsIdLogRoute = ItemsIdLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => ItemsIdRoute,
} as any)
const ItemsIdInfoRoute = ItemsIdInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => ItemsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shopping': typeof ShoppingRoute
  '/items/$id': typeof ItemsIdRouteWithChildren
  '/items/new': typeof ItemsNewRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/settings/': typeof SettingsIndexRoute
  '/items/$id/info': typeof ItemsIdInfoRoute
  '/items/$id/log': typeof ItemsIdLogRoute
  '/items/$id/tags': typeof ItemsIdTagsRoute
  '/items/$id/': typeof ItemsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shopping': typeof ShoppingRoute
  '/items/new': typeof ItemsNewRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/settings': typeof SettingsIndexRoute
  '/items/$id/info': typeof ItemsIdInfoRoute
  '/items/$id/log': typeof ItemsIdLogRoute
  '/items/$id/tags': typeof ItemsIdTagsRoute
  '/items/$id': typeof ItemsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shopping': typeof ShoppingRoute
  '/items/$id': typeof ItemsIdRouteWithChildren
  '/items/new': typeof ItemsNewRoute
  '/settings/tags': typeof SettingsTagsRoute
  '/settings/': typeof SettingsIndexRoute
  '/items/$id/info': typeof ItemsIdInfoRoute
  '/items/$id/log': typeof ItemsIdLogRoute
  '/items/$id/tags': typeof ItemsIdTagsRoute
  '/items/$id/': typeof ItemsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shopping'
    | '/items/$id'
    | '/items/new'
    | '/settings/tags'
    | '/settings/'
    | '/items/$id/info'
    | '/items/$id/log'
    | '/items/$id/tags'
    | '/items/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shopping'
    | '/items/new'
    | '/settings/tags'
    | '/settings'
    | '/items/$id/info'
    | '/items/$id/log'
    | '/items/$id/tags'
    | '/items/$id'
  id:
    | '__root__'
    | '/'
    | '/shopping'
    | '/items/$id'
    | '/items/new'
    | '/settings/tags'
    | '/settings/'
    | '/items/$id/info'
    | '/items/$id/log'
    | '/items/$id/tags'
    | '/items/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShoppingRoute: typeof ShoppingRoute
  ItemsIdRoute: typeof ItemsIdRouteWithChildren
  ItemsNewRoute: typeof ItemsNewRoute
  SettingsTagsRoute: typeof SettingsTagsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tags': {
      id: '/settings/tags'
      path: '/settings/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof SettingsTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/new': {
      id: '/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof ItemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id/': {
      id: '/items/$id/'
      path: '/'
      fullPath: '/items/$id/'
      preLoaderRoute: typeof ItemsIdIndexRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/items/$id/tags': {
      id: '/items/$id/tags'
      path: '/tags'
      fullPath: '/items/$id/tags'
      preLoaderRoute: typeof ItemsIdTagsRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/items/$id/log': {
      id: '/items/$id/log'
      path: '/log'
      fullPath: '/items/$id/log'
      preLoaderRoute: typeof ItemsIdLogRouteImport
      parentRoute: typeof ItemsIdRoute
    }
    '/items/$id/info': {
      id: '/items/$id/info'
      path: '/info'
      fullPath: '/items/$id/info'
      preLoaderRoute: typeof ItemsIdInfoRouteImport
      parentRoute: typeof ItemsIdRoute
    }
  }
}

interface ItemsIdRouteChildren {
  ItemsIdInfoRoute: typeof ItemsIdInfoRoute
  ItemsIdLogRoute: typeof ItemsIdLogRoute
  ItemsIdTagsRoute: typeof ItemsIdTagsRoute
  ItemsIdIndexRoute: typeof ItemsIdIndexRoute
}

const ItemsIdRouteChildren: ItemsIdRouteChildren = {
  ItemsIdInfoRoute: ItemsIdInfoRoute,
  ItemsIdLogRoute: ItemsIdLogRoute,
  ItemsIdTagsRoute: ItemsIdTagsRoute,
  ItemsIdIndexRoute: ItemsIdIndexRoute,
}

const ItemsIdRouteWithChildren =
  ItemsIdRoute._addFileChildren(ItemsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShoppingRoute: ShoppingRoute,
  ItemsIdRoute: ItemsIdRouteWithChildren,
  ItemsNewRoute: ItemsNewRoute,
  SettingsTagsRoute: SettingsTagsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
